version: '3.8'

services:
  api:
    build:
      context: ./
      # Use this to ensure Coolify builds correctly if Dockerfile isn't standard
      dockerfile: Dockerfile 
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      psqldbgame:
        condition: service_healthy
    networks:
      - game-net
    restart: on-failure

  psqldbgame:
    image: postgres:11-alpine
    container_name: psqldbgame
    restart: always
    # Mapping 5432:5432 is standard for Postgres. 
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - psql_data:/var/lib/postgresql/data
    networks:
      - game-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


networks:
  game-net:
    driver: bridge

volumes:
  psql_data:
